
repositories {
    mavenCentral()
    maven { url 'https://meteordev.org' }
    maven { url 'https://meteordev.org' }
    maven { url 'https://fabricmc.net' }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings "net.fabricmc:yarn:1.21.1+build.3:v2"
    modImplementation "net.fabricmc:fabric-loader:0.15.11"

    // Верная библиотека Meteor Client для версии 1.21.1
    modImplementation "minegame153:meteor-client:0.5.8-SNAPSHOT"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
