pluginManagement {
    repositories {
        maven { url = "https://fabricmc.net" }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = "https://fabricmc.net" }
        maven { url = "https://jitpack.io" }
        maven { url = "https://meteorclient.com" }
    }
}

rootProject.name = 'meteor-addon'
